[2025-03-02T07:56:19.915+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-02T07:56:19.933+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping_pipeline_gcs.install_requirements scheduled__2025-03-01T00:00:00+00:00 [queued]>
[2025-03-02T07:56:19.937+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping_pipeline_gcs.install_requirements scheduled__2025-03-01T00:00:00+00:00 [queued]>
[2025-03-02T07:56:19.938+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-03-02T07:56:19.944+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): install_requirements> on 2025-03-01 00:00:00+00:00
[2025-03-02T07:56:19.953+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=663) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-02T07:56:19.957+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scraping_pipeline_gcs', 'install_requirements', 'scheduled__2025-03-01T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp3dw0s_95']
[2025-03-02T07:56:19.958+0000] {standard_task_runner.py:72} INFO - Started process 665 to run task
[2025-03-02T07:56:19.958+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask install_requirements
[2025-03-02T07:56:20.006+0000] {task_command.py:467} INFO - Running <TaskInstance: scraping_pipeline_gcs.install_requirements scheduled__2025-03-01T00:00:00+00:00 [running]> on host 8b8ee4ab00d2
[2025-03-02T07:56:20.056+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping_pipeline_gcs' AIRFLOW_CTX_TASK_ID='install_requirements' AIRFLOW_CTX_EXECUTION_DATE='2025-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-01T00:00:00+00:00'
[2025-03-02T07:56:20.061+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-02T07:56:20.062+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-02T07:56:20.062+0000] {logging_mixin.py:190} INFO - Current task name:install_requirements state:running start_date:2025-03-02 07:56:19.933537+00:00
[2025-03-02T07:56:20.062+0000] {logging_mixin.py:190} INFO - Dag name:scraping_pipeline_gcs and current dag run status:running
[2025-03-02T07:56:20.063+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-02T07:56:20.064+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-02T07:56:20.065+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'pip install -r /opt/***/dags/requirements.txt']
[2025-03-02T07:56:20.074+0000] {subprocess.py:99} INFO - Output:
[2025-03-02T07:56:21.701+0000] {subprocess.py:106} INFO - 
[2025-03-02T07:56:21.704+0000] {subprocess.py:106} INFO - [notice] A new release of pip is available: 25.0 -> 25.0.1
[2025-03-02T07:56:21.704+0000] {subprocess.py:106} INFO - [notice] To update, run: pip install --upgrade pip
[2025-03-02T07:56:21.705+0000] {subprocess.py:106} INFO - ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/opt/***/dags/requirements.txt'
[2025-03-02T07:56:21.746+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-02T07:56:21.771+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-02T07:56:21.783+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-02T07:56:21.784+0000] {logging_mixin.py:190} INFO - Task start:2025-03-02 07:56:19.933537+00:00 end:2025-03-02 07:56:21.782138+00:00 duration:1.848601
[2025-03-02T07:56:21.786+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): install_requirements> dag:<DAG: scraping_pipeline_gcs> dagrun:<DagRun scraping_pipeline_gcs @ 2025-03-01 00:00:00+00:00: scheduled__2025-03-01T00:00:00+00:00, state:running, queued_at: 2025-03-02 07:22:18.989495+00:00. externally triggered: False>
[2025-03-02T07:56:21.787+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2025-03-02T07:56:21.788+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=scraping_pipeline_gcs, task_id=install_requirements, run_id=scheduled__2025-03-01T00:00:00+00:00, execution_date=20250301T000000, start_date=20250302T075619, end_date=20250302T075621
[2025-03-02T07:56:22.541+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-02T07:56:22.541+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 13 for task install_requirements (Bash command failed. The command returned a non-zero exit code 1.; 665)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-02T07:56:22.586+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-02T07:56:22.634+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-02T07:56:22.638+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
